language: python
python:
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

env:
  global:
  - DATABASE_URI='postgres://soqerjpq:YZCacYhoNGHPtbX0zixiq7Lu81MrRJ1U@salt.db.elephantsql.com:5432/soqerjpq'

script:
  - nosetests

after_success:
  - codecov

services:
  - postgresql
